#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Nov  5 17:09:03 2023

@author: dale
"""

from sqlalchemy import Column, String, Integer, Float
from sqlalchemy.dialects.postgresql import JSONB
from db.base_class import Base


class Product_Types(Base):
    __table_args__ = {"schema": "public"}

    product_type = Column(String, nullable=False, primary_key=True)
    extra_data = Column(JSONB, nullable=True)


class Terp_Table(Base):
    __tablename__ = 'terp_table'
    flower_id = Column(Integer, primary_key=True, nullable=True)
    concentrate_id = Column(Integer, primary_key=True, nullable=True)
    pre_roll_id = Column(Integer, primary_key=True, nullable=True)
    edible_id = Column(Integer, primary_key=True, nullable=True)
    product_type = Column(String, nullable=True)

    alpha_bergamotene = Column(Float, nullable=True)
    alpha_beta_cis_ocimene = Column(Float, nullable=True)
    alpha_beta_pinene = Column(Float, nullable=True)
    alpha_beta_thujene = Column(Float, nullable=True)
    alpha_bisabolene = Column(Float, nullable=True)
    alpha_bisabolol = Column(Float, nullable=True)
    alpha_cedrene = Column(Float, nullable=True)
    alpha_fenchene = Column(Float, nullable=True)
    alpha_humulene = Column(Float, nullable=True)
    alpha_humulene_epoxide_i = Column(Float, nullable=True)
    alpha_phellandrene = Column(Float, nullable=True)
    alpha_pinene = Column(Float, nullable=True)
    alpha_terpinene = Column(Float, nullable=True)
    alpha_terpineol = Column(Float, nullable=True)
    alpha_terpinolene = Column(Float, nullable=True)
    alpha_thujene = Column(Float, nullable=True)
    alpha_zingiberene = Column(Float, nullable=True)
    beta_asarone = Column(Float, nullable=True)
    beta_bisabolene = Column(Float, nullable=True)
    beta_caryophyllene = Column(Float, nullable=True)
    beta_caryophyllene_oxide = Column(Float, nullable=True)
    beta_farnesene = Column(Float, nullable=True)
    beta_myrcene = Column(Float, nullable=True)
    beta_ocimene = Column(Float, nullable=True)
    beta_pinene = Column(Float, nullable=True)
    beta_selinene = Column(Float, nullable=True)
    beta_terpinene = Column(Float, nullable=True)
    camphene = Column(Float, nullable=True)
    caryophyllene = Column(Float, nullable=True)
    caryophyllene_oxide = Column(Float, nullable=True)
    cis_nerolidol = Column(Float, nullable=True)
    cis_beta_ocimene = Column(Float, nullable=True)
    delta_3_carene = Column(Float, nullable=True)
    delta_limonene = Column(Float, nullable=True)
    eucalyptol = Column(Float, nullable=True)
    gamma_terpinene = Column(Float, nullable=True)
    geraniol = Column(Float, nullable=True)
    guaiol = Column(Float, nullable=True)
    isoborneol = Column(Float, nullable=True)
    isopulegol = Column(Float, nullable=True)
    limonene = Column(Float, nullable=True)
    linalool = Column(Float, nullable=True)
    myrcene = Column(Float, nullable=True)
    nerolidol = Column(Float, nullable=True)
    ocimene = Column(Float, nullable=True)
    p_cymene = Column(Float, nullable=True)
    para_cymene = Column(Float, nullable=True)
    phellandrene = Column(Float, nullable=True)
    terpineol = Column(Float, nullable=True)
    terpinolene = Column(Float, nullable=True)
    trans_nerolidol = Column(Float, nullable=True)
    trans_ocimene = Column(Float, nullable=True)
    y_terpinene = Column(Float, nullable=True)


class FlowerTerpTable(Base):
    __tablename__ = 'combined_flower_terp'
    flower_id = Column(Integer, primary_key=True, nullable=True)
    product_type = Column(String, nullable=True)
    strain_type = Column(String, nullable=True)
    strain = Column(String, nullable=True)
    cultivator = Column(String, nullable=True)
    card_path = Column(String, nullable=True)
    is_mystery = Column(String, nullable=True)
    voting_open = Column(String, nullable=True)

    alpha_bergamotene = Column(Float, nullable=True)
    alpha_beta_cis_ocimene = Column(Float, nullable=True)
    alpha_beta_pinene = Column(Float, nullable=True)
    alpha_beta_thujene = Column(Float, nullable=True)
    alpha_bisabolene = Column(Float, nullable=True)
    alpha_bisabolol = Column(Float, nullable=True)
    alpha_cedrene = Column(Float, nullable=True)
    alpha_fenchene = Column(Float, nullable=True)
    alpha_humulene = Column(Float, nullable=True)
    alpha_humulene_epoxide_i = Column(Float, nullable=True)
    alpha_phellandrene = Column(Float, nullable=True)
    alpha_pinene = Column(Float, nullable=True)
    alpha_terpinene = Column(Float, nullable=True)
    alpha_terpineol = Column(Float, nullable=True)
    alpha_terpinolene = Column(Float, nullable=True)
    alpha_thujene = Column(Float, nullable=True)
    alpha_zingiberene = Column(Float, nullable=True)
    beta_asarone = Column(Float, nullable=True)
    beta_bisabolene = Column(Float, nullable=True)
    beta_caryophyllene = Column(Float, nullable=True)
    beta_caryophyllene_oxide = Column(Float, nullable=True)
    beta_farnesene = Column(Float, nullable=True)
    beta_myrcene = Column(Float, nullable=True)
    beta_ocimene = Column(Float, nullable=True)
    beta_pinene = Column(Float, nullable=True)
    beta_selinene = Column(Float, nullable=True)
    beta_terpinene = Column(Float, nullable=True)
    camphene = Column(Float, nullable=True)
    caryophyllene = Column(Float, nullable=True)
    caryophyllene_oxide = Column(Float, nullable=True)
    cis_nerolidol = Column(Float, nullable=True)
    cis_beta_ocimene = Column(Float, nullable=True)
    delta_3_carene = Column(Float, nullable=True)
    delta_limonene = Column(Float, nullable=True)
    eucalyptol = Column(Float, nullable=True)
    gamma_terpinene = Column(Float, nullable=True)
    geraniol = Column(Float, nullable=True)
    guaiol = Column(Float, nullable=True)
    isoborneol = Column(Float, nullable=True)
    isopulegol = Column(Float, nullable=True)
    limonene = Column(Float, nullable=True)
    linalool = Column(Float, nullable=True)
    myrcene = Column(Float, nullable=True)
    nerolidol = Column(Float, nullable=True)
    ocimene = Column(Float, nullable=True)
    p_cymene = Column(Float, nullable=True)
    para_cymene = Column(Float, nullable=True)
    phellandrene = Column(Float, nullable=True)
    terpineol = Column(Float, nullable=True)
    terpinolene = Column(Float, nullable=True)
    trans_nerolidol = Column(Float, nullable=True)
    trans_ocimene = Column(Float, nullable=True)
    y_terpinene = Column(Float, nullable=True)


class ConcentrateTerpTable(Base):
    __tablename__ = 'combined_concentrate_terp'
    concentrate_id = Column(Integer, primary_key=True, nullable=True)
    product_type = Column(String, nullable=True)
    strain_type = Column(String, nullable=True)
    strain = Column(String, nullable=True)
    cultivator = Column(String, nullable=True)
    card_path = Column(String, nullable=True)
    is_mystery = Column(String, nullable=True)
    voting_open = Column(String, nullable=True)

    alpha_bergamotene = Column(Float, nullable=True)
    alpha_beta_cis_ocimene = Column(Float, nullable=True)
    alpha_beta_pinene = Column(Float, nullable=True)
    alpha_beta_thujene = Column(Float, nullable=True)
    alpha_bisabolene = Column(Float, nullable=True)
    alpha_bisabolol = Column(Float, nullable=True)
    alpha_cedrene = Column(Float, nullable=True)
    alpha_fenchene = Column(Float, nullable=True)
    alpha_humulene = Column(Float, nullable=True)
    alpha_humulene_epoxide_i = Column(Float, nullable=True)
    alpha_phellandrene = Column(Float, nullable=True)
    alpha_pinene = Column(Float, nullable=True)
    alpha_terpinene = Column(Float, nullable=True)
    alpha_terpineol = Column(Float, nullable=True)
    alpha_terpinolene = Column(Float, nullable=True)
    alpha_thujene = Column(Float, nullable=True)
    alpha_zingiberene = Column(Float, nullable=True)
    beta_asarone = Column(Float, nullable=True)
    beta_bisabolene = Column(Float, nullable=True)
    beta_caryophyllene = Column(Float, nullable=True)
    beta_caryophyllene_oxide = Column(Float, nullable=True)
    beta_farnesene = Column(Float, nullable=True)
    beta_myrcene = Column(Float, nullable=True)
    beta_ocimene = Column(Float, nullable=True)
    beta_pinene = Column(Float, nullable=True)
    beta_selinene = Column(Float, nullable=True)
    beta_terpinene = Column(Float, nullable=True)
    camphene = Column(Float, nullable=True)
    caryophyllene = Column(Float, nullable=True)
    caryophyllene_oxide = Column(Float, nullable=True)
    cis_nerolidol = Column(Float, nullable=True)
    cis_beta_ocimene = Column(Float, nullable=True)
    delta_3_carene = Column(Float, nullable=True)
    delta_limonene = Column(Float, nullable=True)
    eucalyptol = Column(Float, nullable=True)
    gamma_terpinene = Column(Float, nullable=True)
    geraniol = Column(Float, nullable=True)
    guaiol = Column(Float, nullable=True)
    isoborneol = Column(Float, nullable=True)
    isopulegol = Column(Float, nullable=True)
    limonene = Column(Float, nullable=True)
    linalool = Column(Float, nullable=True)
    myrcene = Column(Float, nullable=True)
    nerolidol = Column(Float, nullable=True)
    ocimene = Column(Float, nullable=True)
    p_cymene = Column(Float, nullable=True)
    para_cymene = Column(Float, nullable=True)
    phellandrene = Column(Float, nullable=True)
    terpineol = Column(Float, nullable=True)
    terpinolene = Column(Float, nullable=True)
    trans_nerolidol = Column(Float, nullable=True)
    trans_ocimene = Column(Float, nullable=True)
    y_terpinene = Column(Float, nullable=True)


class EdibleTerpTable(Base):
    __tablename__ = 'combined_edible_terp'
    edible_id = Column(Integer, primary_key=True, nullable=True)
    product_type = Column(String, nullable=True)
    strain_type = Column(String, nullable=True)
    strain = Column(String, nullable=True)
    cultivator = Column(String, nullable=True)
    card_path = Column(String, nullable=True)
    is_mystery = Column(String, nullable=True)
    voting_open = Column(String, nullable=True)

    alpha_bergamotene = Column(Float, nullable=True)
    alpha_beta_cis_ocimene = Column(Float, nullable=True)
    alpha_beta_pinene = Column(Float, nullable=True)
    alpha_beta_thujene = Column(Float, nullable=True)
    alpha_bisabolene = Column(Float, nullable=True)
    alpha_bisabolol = Column(Float, nullable=True)
    alpha_cedrene = Column(Float, nullable=True)
    alpha_fenchene = Column(Float, nullable=True)
    alpha_humulene = Column(Float, nullable=True)
    alpha_humulene_epoxide_i = Column(Float, nullable=True)
    alpha_phellandrene = Column(Float, nullable=True)
    alpha_pinene = Column(Float, nullable=True)
    alpha_terpinene = Column(Float, nullable=True)
    alpha_terpineol = Column(Float, nullable=True)
    alpha_terpinolene = Column(Float, nullable=True)
    alpha_thujene = Column(Float, nullable=True)
    alpha_zingiberene = Column(Float, nullable=True)
    beta_asarone = Column(Float, nullable=True)
    beta_bisabolene = Column(Float, nullable=True)
    beta_caryophyllene = Column(Float, nullable=True)
    beta_caryophyllene_oxide = Column(Float, nullable=True)
    beta_farnesene = Column(Float, nullable=True)
    beta_myrcene = Column(Float, nullable=True)
    beta_ocimene = Column(Float, nullable=True)
    beta_pinene = Column(Float, nullable=True)
    beta_selinene = Column(Float, nullable=True)
    beta_terpinene = Column(Float, nullable=True)
    camphene = Column(Float, nullable=True)
    caryophyllene = Column(Float, nullable=True)
    caryophyllene_oxide = Column(Float, nullable=True)
    cis_nerolidol = Column(Float, nullable=True)
    cis_beta_ocimene = Column(Float, nullable=True)
    delta_3_carene = Column(Float, nullable=True)
    delta_limonene = Column(Float, nullable=True)
    eucalyptol = Column(Float, nullable=True)
    gamma_terpinene = Column(Float, nullable=True)
    geraniol = Column(Float, nullable=True)
    guaiol = Column(Float, nullable=True)
    isoborneol = Column(Float, nullable=True)
    isopulegol = Column(Float, nullable=True)
    limonene = Column(Float, nullable=True)
    linalool = Column(Float, nullable=True)
    myrcene = Column(Float, nullable=True)
    nerolidol = Column(Float, nullable=True)
    ocimene = Column(Float, nullable=True)
    p_cymene = Column(Float, nullable=True)
    para_cymene = Column(Float, nullable=True)
    phellandrene = Column(Float, nullable=True)
    terpineol = Column(Float, nullable=True)
    terpinolene = Column(Float, nullable=True)
    trans_nerolidol = Column(Float, nullable=True)
    trans_ocimene = Column(Float, nullable=True)
    y_terpinene = Column(Float, nullable=True)


class PreRollTerpTable(Base):
    __tablename__ = 'combined_pre_roll_terp'
    pre_roll_id = Column(Integer, primary_key=True, nullable=True)
    strain_type = Column(String, nullable=True)
    strain_type = Column(String, nullable=True)
    strain = Column(String, nullable=True)
    cultivator = Column(String, nullable=True)
    card_path = Column(String, nullable=True)
    is_mystery = Column(String, nullable=True)
    voting_open = Column(String, nullable=True)

    alpha_bergamotene = Column(Float, nullable=True)
    alpha_beta_cis_ocimene = Column(Float, nullable=True)
    alpha_beta_pinene = Column(Float, nullable=True)
    alpha_beta_thujene = Column(Float, nullable=True)
    alpha_bisabolene = Column(Float, nullable=True)
    alpha_bisabolol = Column(Float, nullable=True)
    alpha_cedrene = Column(Float, nullable=True)
    alpha_fenchene = Column(Float, nullable=True)
    alpha_humulene = Column(Float, nullable=True)
    alpha_humulene_epoxide_i = Column(Float, nullable=True)
    alpha_phellandrene = Column(Float, nullable=True)
    alpha_pinene = Column(Float, nullable=True)
    alpha_terpinene = Column(Float, nullable=True)
    alpha_terpineol = Column(Float, nullable=True)
    alpha_terpinolene = Column(Float, nullable=True)
    alpha_thujene = Column(Float, nullable=True)
    alpha_zingiberene = Column(Float, nullable=True)
    beta_asarone = Column(Float, nullable=True)
    beta_bisabolene = Column(Float, nullable=True)
    beta_caryophyllene = Column(Float, nullable=True)
    beta_caryophyllene_oxide = Column(Float, nullable=True)
    beta_farnesene = Column(Float, nullable=True)
    beta_myrcene = Column(Float, nullable=True)
    beta_ocimene = Column(Float, nullable=True)
    beta_pinene = Column(Float, nullable=True)
    beta_selinene = Column(Float, nullable=True)
    beta_terpinene = Column(Float, nullable=True)
    camphene = Column(Float, nullable=True)
    caryophyllene = Column(Float, nullable=True)
    caryophyllene_oxide = Column(Float, nullable=True)
    cis_nerolidol = Column(Float, nullable=True)
    cis_beta_ocimene = Column(Float, nullable=True)
    delta_3_carene = Column(Float, nullable=True)
    delta_limonene = Column(Float, nullable=True)
    eucalyptol = Column(Float, nullable=True)
    gamma_terpinene = Column(Float, nullable=True)
    geraniol = Column(Float, nullable=True)
    guaiol = Column(Float, nullable=True)
    isoborneol = Column(Float, nullable=True)
    isopulegol = Column(Float, nullable=True)
    limonene = Column(Float, nullable=True)
    linalool = Column(Float, nullable=True)
    myrcene = Column(Float, nullable=True)
    nerolidol = Column(Float, nullable=True)
    ocimene = Column(Float, nullable=True)
    p_cymene = Column(Float, nullable=True)
    para_cymene = Column(Float, nullable=True)
    phellandrene = Column(Float, nullable=True)
    terpineol = Column(Float, nullable=True)
    terpinolene = Column(Float, nullable=True)
    trans_nerolidol = Column(Float, nullable=True)
    trans_ocimene = Column(Float, nullable=True)
    y_terpinene = Column(Float, nullable=True)